version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: lemenu-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - minio-network

  # Optional: MinIO Client for bucket management
  minio-client:
    image: minio/mc:latest
    container_name: lemenu-minio-client
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - minio-network
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin123; do
        echo 'Waiting for MinIO to be ready...'
        sleep 2
      done
      /usr/bin/mc mb minio/lemenu-uploads --ignore-existing
      /usr/bin/mc policy set public minio/lemenu-uploads
      echo 'MinIO setup complete!'
      tail -f /dev/null
      "

volumes:
  minio_data:
    driver: local

networks:
  minio-network:
    driver: bridge
